# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3125fee9f256d8526d601c680e34db66745943541e1404985dbf1a1975bb4ebd7c916863bbadb6dfc29b30a9b3ee0763dc262cd4a4acc09ed2bcbf06ec20a986

test:
  secret_key_base: c720de0d1c4cea1d811f2eac16fceefcf6978cb7e6d694ae4c65a9d1fec1ade6a2125b4b6bf846bb56fb09d62f0c75d6237077651444b019b6dd751b14e02e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
